### ISSUE TITLE
ConstrainedArray don't support multiple value

### ISSUE THREAD

**Issue by VJubert** [lifebeyondfife/Decider#13]
Hi Iain,

If I modify a bit data from your example project "Optimisation" : `var array = new ConstrainedArray(new int[] { 0, 23, 52, 62, 73, 73, 47, 20, 87, 27 });` (the first 73 was a 75 in your example)

I got an error because `Dictionary` and `SortedList` don't support same multiple values : `System.ArgumentException : 'An item with the same key has already been added. Key: 73'`

**Comment by lifebeyondfife** [comment]
Thanks for bearing with the wait Valentin - feedback was much appreciated. Fix for this error is now in: https://github.com/lifebeyondfife/Decider/commit/05a37e2de8b3c73693c4d7e31e940d8cc24f1676

Cheers,
Iain
