### ISSUE TITLE
Using negative Integer values

### ISSUE THREAD

**Issue by HenrikSel13** [lifebeyondfife/Decider#19]
I'm trying to use Decider with negative integer values to solve expressions like the example below. Unfortunately, an exception is thrown or it goes into an infinite loop. Is there a solution or is there another syntax I have to use to solve problems like this? Thank you! 

`           var avar = new VariableInteger("avar", -2,5);
            var bvar = new VariableInteger("bvar", -1,5);

            var constraints = new List<IConstraint>
                {
                    new ConstraintInteger((avar>bvar)==1)
		};

			var variables = new [] { avar , bvar};
			IState<int> state = new StateInteger(variables, constraints);

            state.StartSearch(out StateOperationResult searchResult, out IList<IDictionary<string, IVariable<int>>> solutions);
`

**Comment by lifebeyondfife** [comment]
Hello Henrik,

That definitely looks wrong i.e. negative values should work perfectly with a constrained integer variable.

I will make some time this week to look into this in the hope that it's a straightforward bug to fix. Expect an update soon.

Thanks for your interest in using Decider.

**Comment by lifebeyondfife** [comment]
Traced the issue back to this line of code: https://github.com/lifebeyondfife/Decider/blob/master/Csp/Integer/DomainBinaryInteger.cs#L37

For negative numbers indices, this can result in a negative array index attempt.

I'm a little surprised - you must be the first person to use this library with a negative constrained integer. This class contains a compact (bitwise) representation of a variable domain. With some offset tracking for negative integers, it should be possible to create a fix.

Stay tuned.

**Comment by lifebeyondfife** [comment]
The latest version of the code has fixed the issue with negative domain values. I'll update the nuget package library at some point (please let me know if this is urgent) but the fix is in the master branch if you want to grab the source code.

Thanks again for reporting Henrik, much appreciated.

**Comment by lifebeyondfife** [comment]
Updated nuget package. If you install now, version 0.3.9 (latest) will contain the fix.
