### ISSUE TITLE
Extended syntax for ConstraintInteger's

### ISSUE THREAD

**Issue by dlidstrom** [lifebeyondfife/Decider#24]
I was trying to model this riddle:

    [?] [?] [?]
     6   8   2 One number is correct and well placed
     6   1   4 One number is correct but wrong placed
     7   8   0 One number is correct but wrong placed

I am using this as an example to learn more about this nice library. My first attempt goes something like this:

```csharp
var validElements = new List<int>
{
    0, 1, 2, 4, 6, 7, 8,
};
var first = new VariableInteger("first", validElements);
var second = new VariableInteger("second", validElements);
var third = new VariableInteger("third", validElements);
var constraint1 = new ConstraintInteger(first == 6 && second != 8 && third != 2);
```

This is where I got stuck. The compiler complains about && above:

    In order for 'ExpressionInteger.operator &(ExpressionInteger, ExpressionInteger)' to be applicable as a short circuit operator, its declaring type 'ExpressionInteger' must define operator true and operator false

Would it be useful to have these operators?
CSP is very interesting. Would you be able to give some guidance on how to model the riddle?
Thanks!

**Comment by lifebeyondfife** [comment]
Thanks for the query Daniel. The logical AND operator is available i.e. &,
as opposed to &&. I could have overridden conditional AND if I'd overridden
true and false but didn't want to go that far.

Check the operator precedence though, you may need to say ((x == 1) & (y !=
3)) etc.

Hope this helps. If not give me another shout and I'll load your code
myself and try to get it working.

**Comment by dlidstrom** [comment]
I got it working!

```csharp
private static void Decide()
{
    /**
     * [?] [?] [?]
     * 6 8 2 One number is correct and well placed
     * 6 1 4 One number is correct but wrong placed
     * 7 8 0 One number is correct but wrong placed
     */
    var validElements = new List<int>
    {
        0, 1, 2, 4, 6, 7, 8,
    };
    var first = new VariableInteger("first", validElements);
    var second = new VariableInteger("second", validElements);
    var third = new VariableInteger("third", validElements);
    var constraint1 = new ConstraintInteger(
        ((first == 6) & (second != 8 & second != 2) & (third != 8 & third != 2)) // 6 is correct and well placed
        | ((first != 6 & first != 2) & (second == 8) & (third != 6 & third != 2)) // 8 is correct and well placed
        | ((first != 6 & first != 8) & (second != 6 & second != 8) & (third == 2))); // 2 is correct and well placed

    // one number is correct but wrong placed
    var constraint2 = new ConstraintInteger(
        (first == 1 | first == 4 | second == 6 | second == 4 | third == 6 | third == 1)
        & (first != 6 & second != 1 & third != 4));

    // one number is correct but wrong placed
    var constraint3 = new ConstraintInteger(
        (first == 8 | first == 0 | second == 7 | second == 0 | third == 7 | third == 8)
        & (first != 7 & second != 8 & third != 0));

    var constraints = new List<IConstraint>
        {
            constraint1, constraint2, constraint3,
        };

    var variables = new[] { first, second, third, };
    IState<int> state = new StateInteger(variables, constraints);

    state.StartSearch(out StateOperationResult searchResult);

    Console.WriteLine("Runtime:\t{0}\nBacktracks:\t{1}\n", state.Runtime, state.Backtracks);
    Console.WriteLine($"[{first}] [{second}] [{third}]");
}
```

It gives the (surprising to me) answer [1] [0] [2].
Thanks!

**Comment by lifebeyondfife** [comment]
Great to hear that you were able to get your problem encoded. Thanks for sharing.
