### ISSUE TITLE
MIT or GPL?

### ISSUE THREAD

**Issue by cmdkeen** [lifebeyondfife/Decider#7]
The project Readme says decider is MIT but the file headers are all GPL 3. Would you mind clarifying which is correct.

Thanks.

Chris

**Comment by lifebeyondfife** [comment]
Thanks for getting in touch, Chris. I'm always keen to help those interested in Decider, and hear about what people are doing with it.

It was originally GPL3 (hence the file headers) but I changed the licence to MIT when my then employers Moody's wanted to use it in one of their applications.

I can confirm it's available under the MIT licence.

If you'd like me to remove the GPL3 file headers to provide more reassurance, I'm happy to, but I probably won't get round to it until at least the weekend.

All the best,
Iain

**Comment by cmdkeen** [comment]
Thanks Iain, I'm just playing about at the moment so there's no rush. It's proving really useful so far - constrained arrays look like exactly what I'm after, plus having it in C# is fantastic.

**Comment by lifebeyondfife** [comment]
Great to hear. I only put the constrained array feature in relatively recently because I needed it in my Cm93 repo. It was always a feature that I found handy when I used to use Ilog Solver.

Cheers,
Iain

**Comment by lifebeyondfife** [comment]
master branch has been updated to remove all old GPL 3 notices. Hope Decider continues to work well for you.

Cheers,
Iain
